export default {
  AUTH: {
    LOGIN: 'LOGIN',
    LOGIN_WITH_TOKEN: 'LOGIN_WITH_TOKEN',
    REGISTER: 'AUTH_REGISTER',
    RESET_PASSWORD: 'RESET_PASSWORD',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    RESEND_VERIFICATION: 'RESEND_VERIFICATION',
  },
  CURRENT: {
    USERS: 'CURRENT_USER',
  },
  MANAGEMENT: {
    WAREHOUSE: {
      ADD: 'ADD_WAREHOUSE',
      GET: 'GET_WAREHOUSES',
      DELETE: 'DELETE_WAREHOUSES',
      PUT: 'PUT_WAREHOUSE',
    },
    STORE: {
      ADD: 'ADD_STORE',
      GET: 'GET_STORES',
      DELETE: 'DELETE_STORES',
      PUT: 'PUT_STORE',
    },
    ARTICLE: {
      ADD: 'ADD_ARTICLE',
      GET: 'GET_ARTICLES',
      GET_AC: 'GET_AC',
      DELETE: 'DELETE_ARTICLES',
      PUT: 'PUT_ARTICLE',
    },
    PRODUCT: {
      ADD: 'ADD_PRODUCT',
      PUT: 'PUT_PRODUCT',
      GET: 'GET_PRODUCTS',
      GET_BRANDS: 'GET_BRANDS',
      GET_BRANDMODELS: 'GET_BRANDMODELS',
      DELETE: 'DELETE_PRODUCTS',
    },
  },
} as const
